/**
 * Auto-generated by scripts/generate-image-captions.ts — do not edit.
 * Content-based captions for job images (vision API). Re-run the script to refresh.
 */

export const JOB_IMAGE_CAPTIONS: Record<string, string> = {
}
